name: Workflow

on:
  push:
    branches:
      - main

jobs:
  first_flow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hello world."
      - name: Dime la fecha
        run: date
      - run: ls -l
