name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm ci
      - name: Prettier Format
        run: pnpm run prettier:format
      - name: Prettier Check
        run: pnpm run prettier:check
      - name: Build
        run: pnpm run build